//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWeb_TH9_Bai1_Bai2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaXuatBan
    {
        public NhaXuatBan()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public int MaNXB { get; set; }
        public string TenNXB { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> DienThoai { get; set; }
    
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
