//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWeb_TH9_Bai1_Bai2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacGia
    {
        public TacGia()
        {
            this.ThamGias = new HashSet<ThamGia>();
        }
    
        public int MaTacGia { get; set; }
        public string TenTacGia { get; set; }
        public string DiaChi { get; set; }
        public string TieuSu { get; set; }
        public Nullable<int> DienThoai { get; set; }
    
        public virtual ICollection<ThamGia> ThamGias { get; set; }
    }
}
